// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    println!("[LocardX] Initializing application core...");

    let state = match locardx_desktop::init_application() {
        Ok(s) => s,
        Err(err) => {
            eprintln!("[LocardX] Critical initialization failure: {}", err);
            std::process::exit(1);
        }
    };

    println!("[LocardX] Core initialized. Launching Tauri desktop shell...");

    tauri::Builder::default()
        .manage(state)
        .invoke_handler(tauri::generate_handler![
            locardx_desktop::commands::get_app_info,
            locardx_desktop::commands::get_authentication_status,
            locardx_desktop::commands::is_first_run,
            locardx_desktop::commands::initialize_admin,
            locardx_desktop::commands::initialize_administrator,
            locardx_desktop::commands::login,
            locardx_desktop::commands::logout,
            locardx_desktop::commands::validate_session,
            locardx_desktop::commands::get_current_user,
            locardx_desktop::commands::get_user,
            locardx_desktop::commands::update_user,
            locardx_desktop::commands::enable_user,
            locardx_desktop::commands::disable_user,
            locardx_desktop::commands::change_user_role,
            locardx_desktop::commands::unlock_user,
            locardx_desktop::commands::create_user,
            locardx_desktop::commands::set_user_enabled,
            locardx_desktop::commands::list_users,
            locardx_desktop::commands::change_password,
            locardx_desktop::commands::get_current_permissions,
            locardx_desktop::commands::check_permission,
            locardx_desktop::commands::list_storage_devices,
            locardx_desktop::commands::calculate_file_hash,
            locardx_desktop::commands::verify_file_hash,
            locardx_desktop::commands::list_integrity_records,
            locardx_desktop::commands::submit_integrity_hash_operation,
            locardx_desktop::commands::submit_integrity_verify_operation,
            locardx_desktop::commands::get_operation,
            locardx_desktop::commands::list_operations,
            locardx_desktop::commands::cancel_operation,
            locardx_desktop::commands::evaluate_operation_safety,
            locardx_desktop::commands::request_destructive_confirmation,
            locardx_desktop::commands::confirm_destructive_operation,
            locardx_desktop::commands::list_safety_evaluations,
            locardx_desktop::commands::evaluate_sanitization_plan,
            locardx_desktop::commands::get_sanitization_methods,
            locardx_desktop::commands::compare_target_snapshot,
            locardx_desktop::commands::get_sanitization_verification_plan,
            locardx_desktop::commands::plan_file_erasure,
            locardx_desktop::commands::plan_folder_erasure,
            locardx_desktop::commands::execute_file_erasure,
            locardx_desktop::commands::execute_folder_erasure,
            locardx_desktop::commands::get_file_erasure_result,
            locardx_desktop::commands::plan_drive_erasure,
            locardx_desktop::commands::execute_drive_erasure_simulation,
            locardx_desktop::commands::execute_drive_erasure_hardware,
            locardx_desktop::commands::get_drive_capabilities,
            locardx_desktop::commands::assess_drive_hardware_capabilities,
            locardx_desktop::commands::get_mock_test_devices,
            locardx_desktop::commands::get_real_storage_devices,
            locardx_desktop::commands::refresh_real_devices,
            locardx_desktop::commands::get_drive_erasure_result,
            locardx_desktop::commands::check_drive_eraser_privileges,
            locardx_desktop::commands::generate_drive_erasure_report,
            locardx_desktop::commands::get_drive_erasure_report,
            locardx_desktop::commands::list_acquisition_sources,
            locardx_desktop::commands::validate_acquisition_source,
            locardx_desktop::commands::validate_acquisition_destination,
            locardx_desktop::commands::create_acquisition_plan,
            locardx_desktop::commands::start_acquisition,
            locardx_desktop::commands::cancel_acquisition,
            locardx_desktop::commands::get_acquisition_progress,
            locardx_desktop::commands::get_acquisition_result,
            locardx_desktop::commands::get_acquisition_artifact,
            locardx_desktop::commands::verify_acquisition_artifact,
            locardx_desktop::commands::list_recovery_sources,
            locardx_desktop::commands::validate_recovery_source,
            locardx_desktop::commands::create_recovery_plan,
            locardx_desktop::commands::start_recovery,
            locardx_desktop::commands::cancel_recovery,
            locardx_desktop::commands::get_recovery_progress,
            locardx_desktop::commands::get_recovery_job,
            locardx_desktop::commands::list_recovery_jobs,
            locardx_desktop::commands::get_recovered_files,
            locardx_desktop::commands::export_recovered_files,
            locardx_desktop::commands::get_recovery_report,
            locardx_desktop::commands::create_case,
            locardx_desktop::commands::get_case,
            locardx_desktop::commands::list_cases,
            locardx_desktop::commands::update_case,
            locardx_desktop::commands::update_case_status,
            locardx_desktop::commands::associate_operation_to_case,
            locardx_desktop::commands::list_case_operations,
            locardx_desktop::commands::add_case_evidence,
            locardx_desktop::commands::list_case_evidence,
            locardx_desktop::commands::record_case_custody_event,
            locardx_desktop::commands::get_case_timeline,
            locardx_desktop::commands::get_case_summary,
            locardx_desktop::commands::generate_case_report,
            locardx_desktop::commands::get_case_report,
            locardx_desktop::commands::list_case_reports,
            locardx_desktop::commands::verify_case_report_integrity,
            locardx_desktop::commands::list_audit_events,
            locardx_desktop::commands::verify_audit_chain,
        ])
        .run(tauri::generate_context!())
        .expect("Error while running LocardX Tauri desktop application");
}
